In [1]:
import matplotlib as plt
import numpy as np
from scipy.fftpack import fftfreq, rfft, fft

In [2]:
np.random.seed(2000)

In [3]:
#L = 10
#x = np.random.normal(250.0, 1.0, L)
#y = np.random.normal(320.0, 1.0, L)

#mean_x = np.mean(x)
#mean_y = np.mean(y)

#x_fft = rfft(x - mean_x)
#y_fft = rfft(y - mean_y)

#fps = 2.0
#freqs = fftfreq(x.size, 1 / fps)

#scale = 20.0
#dslice = slice(1, L // 2)

#fs = freqs[dslice]
#xf = scale * np.log10(x_fft[dslice])
#yf = scale * np.log10(y_fft[dslice])

In [4]:
def calc_psd(vals, N, dt):
    temp = np.abs(fft(vals))**2 * dt / N
    psd = temp[:N//2]
    psd += temp[-1:-N//2 - 1:-1]
    return psd[1:]

In [5]:
L = 10
fps = 2.0
dt = 1 / fps
x = np.random.normal(250.0, 1.0, L)
y = np.random.normal(320.0, 1.0, L)

delta_f = fps / L
psd_x = calc_psd(x, L, dt)
psd_y = calc_psd(y, L, dt)

freq = delta_f * np.arange(L//2)
freq = freq[1:]

In [6]:
freq

array([0.2, 0.4, 0.6, 0.8])

In [7]:
psd_x

array([1.3022891 , 2.4072877 , 2.96332612, 1.13724273])

In [8]:
psd_y

array([0.41251254, 0.51454309, 0.56978575, 2.22593171])